# Generated by Django 5.0.4 on 2024-06-05 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Taom haqida izohingiz')),
                ('created', models.CharField(max_length=150, verbose_name='Post qoldirilgan vaqt')),
                ('author_name', models.CharField(max_length=150, verbose_name='Post muallifi')),
            ],
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Taom turi')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Taom nomi')),
                ('price', models.IntegerField(verbose_name='Taom narxi')),
                ('ingidrients', models.TextField(null=True, verbose_name='Taom tarkibi')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.comment', verbose_name='Post muallifi')),
                ('foodtype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.foodtype', verbose_name='taom turi')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='food_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.food', verbose_name='Taom nomi'),
        ),
    ]
